// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Trackr.Api.Api.Accounts;
using Trackr.Api.Api.Categories;
using Trackr.Api.Api.Health;
using Trackr.Api.Api.RecurringTransactions;
using Trackr.Api.Api.Transactions;
namespace Trackr.Api.Api
{
    /// <summary>
    /// Builds and executes requests for operations under \api
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The accounts property</summary>
        public global::Trackr.Api.Api.Accounts.AccountsRequestBuilder Accounts
        {
            get => new global::Trackr.Api.Api.Accounts.AccountsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The categories property</summary>
        public global::Trackr.Api.Api.Categories.CategoriesRequestBuilder Categories
        {
            get => new global::Trackr.Api.Api.Categories.CategoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The health property</summary>
        public global::Trackr.Api.Api.Health.HealthRequestBuilder Health
        {
            get => new global::Trackr.Api.Api.Health.HealthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The recurringTransactions property</summary>
        public global::Trackr.Api.Api.RecurringTransactions.RecurringTransactionsRequestBuilder RecurringTransactions
        {
            get => new global::Trackr.Api.Api.RecurringTransactions.RecurringTransactionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The transactions property</summary>
        public global::Trackr.Api.Api.Transactions.TransactionsRequestBuilder Transactions
        {
            get => new global::Trackr.Api.Api.Transactions.TransactionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Trackr.Api.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Trackr.Api.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
