// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using Trackr.Api.Models;
namespace Trackr.Api.Api.Transactions.Summary.ExpensesByCategory
{
    /// <summary>
    /// Builds and executes requests for operations under \api\transactions\summary\expenses-by-category
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ExpensesByCategoryRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Trackr.Api.Api.Transactions.Summary.ExpensesByCategory.ExpensesByCategoryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExpensesByCategoryRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/transactions/summary/expenses-by-category{?from*,to*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Trackr.Api.Api.Transactions.Summary.ExpensesByCategory.ExpensesByCategoryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExpensesByCategoryRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/transactions/summary/expenses-by-category{?from*,to*}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::Trackr.Api.Models.GetExpensesByCategoryResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Trackr.Api.Models.ErrorResponse">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Trackr.Api.Models.GetExpensesByCategoryResponse?> GetAsync(Action<RequestConfiguration<global::Trackr.Api.Api.Transactions.Summary.ExpensesByCategory.ExpensesByCategoryRequestBuilder.ExpensesByCategoryRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Trackr.Api.Models.GetExpensesByCategoryResponse> GetAsync(Action<RequestConfiguration<global::Trackr.Api.Api.Transactions.Summary.ExpensesByCategory.ExpensesByCategoryRequestBuilder.ExpensesByCategoryRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Trackr.Api.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Trackr.Api.Models.GetExpensesByCategoryResponse>(requestInfo, global::Trackr.Api.Models.GetExpensesByCategoryResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Trackr.Api.Api.Transactions.Summary.ExpensesByCategory.ExpensesByCategoryRequestBuilder.ExpensesByCategoryRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Trackr.Api.Api.Transactions.Summary.ExpensesByCategory.ExpensesByCategoryRequestBuilder.ExpensesByCategoryRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Trackr.Api.Api.Transactions.Summary.ExpensesByCategory.ExpensesByCategoryRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Trackr.Api.Api.Transactions.Summary.ExpensesByCategory.ExpensesByCategoryRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Trackr.Api.Api.Transactions.Summary.ExpensesByCategory.ExpensesByCategoryRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class ExpensesByCategoryRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
            [QueryParameter("from")]
            public Date? From { get; set; }
            [QueryParameter("to")]
            public Date? To { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ExpensesByCategoryRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Trackr.Api.Api.Transactions.Summary.ExpensesByCategory.ExpensesByCategoryRequestBuilder.ExpensesByCategoryRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
