// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Trackr.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AccountType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Checking")]
        #pragma warning disable CS1591
        Checking,
        #pragma warning restore CS1591
        [EnumMember(Value = "Savings")]
        #pragma warning disable CS1591
        Savings,
        #pragma warning restore CS1591
        [EnumMember(Value = "Cash")]
        #pragma warning disable CS1591
        Cash,
        #pragma warning restore CS1591
        [EnumMember(Value = "CreditCard")]
        #pragma warning disable CS1591
        CreditCard,
        #pragma warning restore CS1591
    }
}
