// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Trackr.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AccountColor
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Primary")]
        #pragma warning disable CS1591
        Primary,
        #pragma warning restore CS1591
        [EnumMember(Value = "Secondary")]
        #pragma warning disable CS1591
        Secondary,
        #pragma warning restore CS1591
        [EnumMember(Value = "Tertiary")]
        #pragma warning disable CS1591
        Tertiary,
        #pragma warning restore CS1591
        [EnumMember(Value = "Info")]
        #pragma warning disable CS1591
        Info,
        #pragma warning restore CS1591
        [EnumMember(Value = "Success")]
        #pragma warning disable CS1591
        Success,
        #pragma warning restore CS1591
        [EnumMember(Value = "Warning")]
        #pragma warning disable CS1591
        Warning,
        #pragma warning restore CS1591
    }
}
