// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Trackr.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum BackendDataEntitiesEnumsTransactionType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Income")]
        #pragma warning disable CS1591
        Income,
        #pragma warning restore CS1591
        [EnumMember(Value = "Expense")]
        #pragma warning disable CS1591
        Expense,
        #pragma warning restore CS1591
        [EnumMember(Value = "Transfer")]
        #pragma warning disable CS1591
        Transfer,
        #pragma warning restore CS1591
    }
}
