// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Trackr.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateTransactionRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The accountId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountId { get; set; }
#nullable restore
#else
        public string AccountId { get; set; }
#endif
        /// <summary>The amount property</summary>
        public decimal? Amount { get; set; }
        /// <summary>The categoryId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CategoryId { get; set; }
#nullable restore
#else
        public string CategoryId { get; set; }
#endif
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The occurredOn property</summary>
        public Date? OccurredOn { get; set; }
        /// <summary>The priority property</summary>
        public global::Trackr.Api.Models.ExpensePriority? Priority { get; set; }
        /// <summary>The toAccountId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ToAccountId { get; set; }
#nullable restore
#else
        public string ToAccountId { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Trackr.Api.Models.TransactionType? Type { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Trackr.Api.Models.CreateTransactionRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Trackr.Api.Models.CreateTransactionRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Trackr.Api.Models.CreateTransactionRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accountId", n => { AccountId = n.GetStringValue(); } },
                { "amount", n => { Amount = n.GetDecimalValue(); } },
                { "categoryId", n => { CategoryId = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "occurredOn", n => { OccurredOn = n.GetDateValue(); } },
                { "priority", n => { Priority = n.GetEnumValue<global::Trackr.Api.Models.ExpensePriority>(); } },
                { "toAccountId", n => { ToAccountId = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Trackr.Api.Models.TransactionType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("accountId", AccountId);
            writer.WriteDecimalValue("amount", Amount);
            writer.WriteStringValue("categoryId", CategoryId);
            writer.WriteStringValue("description", Description);
            writer.WriteDateValue("occurredOn", OccurredOn);
            writer.WriteEnumValue<global::Trackr.Api.Models.ExpensePriority>("priority", Priority);
            writer.WriteStringValue("toAccountId", ToAccountId);
            writer.WriteEnumValue<global::Trackr.Api.Models.TransactionType>("type", Type);
        }
    }
}
#pragma warning restore CS0618
