// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Trackr.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ExpensePriority
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Essential")]
        #pragma warning disable CS1591
        Essential,
        #pragma warning restore CS1591
        [EnumMember(Value = "Important")]
        #pragma warning disable CS1591
        Important,
        #pragma warning restore CS1591
        [EnumMember(Value = "Discretionary")]
        #pragma warning disable CS1591
        Discretionary,
        #pragma warning restore CS1591
    }
}
