// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Trackr.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RecurringTransactionResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The accountId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountId { get; set; }
#nullable restore
#else
        public string AccountId { get; set; }
#endif
        /// <summary>The accountName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountName { get; set; }
#nullable restore
#else
        public string AccountName { get; set; }
#endif
        /// <summary>The amount property</summary>
        public decimal? Amount { get; set; }
        /// <summary>The categoryId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CategoryId { get; set; }
#nullable restore
#else
        public string CategoryId { get; set; }
#endif
        /// <summary>The categoryName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CategoryName { get; set; }
#nullable restore
#else
        public string CategoryName { get; set; }
#endif
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The dayOfMonth property</summary>
        public int? DayOfMonth { get; set; }
        /// <summary>The dayOfWeek property</summary>
        public global::Trackr.Api.Models.DayOfWeekObject? DayOfWeek { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The endOn property</summary>
        public Date? EndOn { get; set; }
        /// <summary>The frequency property</summary>
        public global::Trackr.Api.Models.RecurrenceFrequency? Frequency { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The isActive property</summary>
        public bool? IsActive { get; set; }
        /// <summary>The month property</summary>
        public int? Month { get; set; }
        /// <summary>The nextOccurrenceOn property</summary>
        public Date? NextOccurrenceOn { get; set; }
        /// <summary>The priority property</summary>
        public global::Trackr.Api.Models.ExpensePriority? Priority { get; set; }
        /// <summary>The startOn property</summary>
        public Date? StartOn { get; set; }
        /// <summary>The toAccountId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ToAccountId { get; set; }
#nullable restore
#else
        public string ToAccountId { get; set; }
#endif
        /// <summary>The toAccountName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ToAccountName { get; set; }
#nullable restore
#else
        public string ToAccountName { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Trackr.Api.Models.TransactionType? Type { get; set; }
        /// <summary>The updatedAt property</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Trackr.Api.Models.RecurringTransactionResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Trackr.Api.Models.RecurringTransactionResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Trackr.Api.Models.RecurringTransactionResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accountId", n => { AccountId = n.GetStringValue(); } },
                { "accountName", n => { AccountName = n.GetStringValue(); } },
                { "amount", n => { Amount = n.GetDecimalValue(); } },
                { "categoryId", n => { CategoryId = n.GetStringValue(); } },
                { "categoryName", n => { CategoryName = n.GetStringValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "dayOfMonth", n => { DayOfMonth = n.GetIntValue(); } },
                { "dayOfWeek", n => { DayOfWeek = n.GetEnumValue<global::Trackr.Api.Models.DayOfWeekObject>(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "endOn", n => { EndOn = n.GetDateValue(); } },
                { "frequency", n => { Frequency = n.GetEnumValue<global::Trackr.Api.Models.RecurrenceFrequency>(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "isActive", n => { IsActive = n.GetBoolValue(); } },
                { "month", n => { Month = n.GetIntValue(); } },
                { "nextOccurrenceOn", n => { NextOccurrenceOn = n.GetDateValue(); } },
                { "priority", n => { Priority = n.GetEnumValue<global::Trackr.Api.Models.ExpensePriority>(); } },
                { "startOn", n => { StartOn = n.GetDateValue(); } },
                { "toAccountId", n => { ToAccountId = n.GetStringValue(); } },
                { "toAccountName", n => { ToAccountName = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Trackr.Api.Models.TransactionType>(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("accountId", AccountId);
            writer.WriteStringValue("accountName", AccountName);
            writer.WriteDecimalValue("amount", Amount);
            writer.WriteStringValue("categoryId", CategoryId);
            writer.WriteStringValue("categoryName", CategoryName);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteIntValue("dayOfMonth", DayOfMonth);
            writer.WriteEnumValue<global::Trackr.Api.Models.DayOfWeekObject>("dayOfWeek", DayOfWeek);
            writer.WriteStringValue("description", Description);
            writer.WriteDateValue("endOn", EndOn);
            writer.WriteEnumValue<global::Trackr.Api.Models.RecurrenceFrequency>("frequency", Frequency);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("isActive", IsActive);
            writer.WriteIntValue("month", Month);
            writer.WriteDateValue("nextOccurrenceOn", NextOccurrenceOn);
            writer.WriteEnumValue<global::Trackr.Api.Models.ExpensePriority>("priority", Priority);
            writer.WriteDateValue("startOn", StartOn);
            writer.WriteStringValue("toAccountId", ToAccountId);
            writer.WriteStringValue("toAccountName", ToAccountName);
            writer.WriteEnumValue<global::Trackr.Api.Models.TransactionType>("type", Type);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
        }
    }
}
#pragma warning restore CS0618
